dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash

notifcations:
  slack:
    rooms:
      secure: 4HOAaOH6eujlACH2rtq/SvlEV/prvf062RoyCuLVb5kRfL6gokGK32pnlca/0Rls/q+LHglWqF0zYQo5yVqKSUqJaWwhoS8Noy4rqN9GzjNFwjwgJeGuUI+xRSdmRxyG4ZMdOD0sSq1kw9sMvOsmtwecUQ4YAckUb+704UpQu/tgGa/jcgkyVVOB2EIW1DGRbudQCNUwKHHwuNJYMFPOmnY55UuIS+BE1hZMZTq1c3UKrEAaIfnf4PZfFKk4ttx+TSZzmk1cL3EoKQwSI7kJAg+40p1zMNkl38O6ZT/Wlu1Fg5NdR/+XjA0BlsFjJJWQeBA3hUOTqfwwWEP74JTLR167JmZiTBhxP0RTA0lRCIhyCFBvNSIPEuZMMNF8tUOY1Q5rqhfWtTPg1IhAQHwUIvtUCLRqMKIyGu5HXxF0vgJ5bKfM6nKeolUZbkrYrSwWMLRlvAYD/MMlxxXmJxSjYp6AJqvWYv9Hm3cA9asAOovEp0CGRSrwNV3YnNHEZGsoQkTHfoTKDBapIiSvEnoelkpJm26d92PlqQRYdAz5w4VCau9YT8Q19A6RCiWFWoQOqKRh3BJbmBgvFwSmwz77pyDrKisIalXyzMp7mz6lNwNCP08PuZBY9WgMRD0ZBa8l8TrM4BWZWeDM9kXh3vtnG+uQxVf9I0Lfec8ZUZkT9ic=
